const fr = {
  appName : "Todo App",
  home: "Accueil",
  logout: "Déconnecté",
  loginTitle: "Connectez-vous",
  signUpTitle: "Inscription",
  btnSignup: "S'inscrire",
  btnLogin: "Se connecter",
  connection: "Connexion",
  recoveryPassMsgError: "Il y a un problème! Vérifiez l'e-mail",
  register: "S'inscrire",
  registerQuestion: "Vous n'avez pas de compte? Inscrivez-vous ici",
  update: "Mise à jour",
  fullname: "Nom et Prénom",
  first_name: "Nom",
  last_name: "Prénom",
  phone: "Numéro de téléphone",
  email: "Email",
  password: "Mot de pass",
  confirmPassword: "Confirmer le mot de passe",
  date: "Date de naissance",
  newPassword: "Un nouveau mot de passe",
  oldPassword: "Votre mot de passe actuel",
  dontChange:
    "Si vous ne souhaitez pas modifier votre mot de passe, laissez-le vide",
  account: "Compte",
  newAccount: "Créer un nouveau compte",
  IhaveAccount: "J'ai un compte, revenir à la connexion",
  EmailNoValid: "E-mail déjà utilisé ou non valide",
  FieldEmpty: "Le champ est obligatoire.",
  FieldEmptyInput: "Touts les champs est obligatoire.",
  MinPassWord: "Le mot de passe doit contenir plus de 8 caractères",
  PassNotMatch: "Veillez à faire correspondre les deux mot de passe",
  categories: "Catégories",
  noInternet: "Erreur de connexion",
  version: "Version",
  more: "Montre plus",
  notificationAlert:
    "Notification bloquée, accédez aux paramètres de votre système et activez les notifications",
  alert: "Alerte",
  share: "Partager",
  profileUpdate: "Mise à jour de compte",
  profile: "Profile",
  youInfoUpdated: "Modifié avec succès",
  youInfoUpdatedUnsuccess: "Mise à jour infructueuse",
  apply: "Appliquer",
  delete: "supprimer",
  cancel: "Annuler",
  ok: "Ok",
  Add: "Ajouter",
  RegisterFiled:
    "Erreur L'enregistrement du nouveau compte n'a pas été terminé",
  YourInfoNotValid: "Les informations utilisateur ne sont pas valides",
  detail: "Détails",
  status: "Status",
  loginUnsuccessful: "Erreur lors de la connexion",
  active: "Active",
  disactive: "Disactive",
  accountStatus: "Statut du compte",
  deleteIsSuccess: "Supprimer avec succès",
  deleteIsError: "Erreur lors de supprimer",
  addIsSuccess: "Ajouter  avec succès",
  date_created: "Date créée",
  date_updated: "Date modifiée",
  code: "Code",
  help: "Aidez-moi",
  youWelcome: "Bienvenue",
  updatePassword: "Changement de mot de passe",
  error: "Erreur",
  youAccountCreated:
    "Compte créé avec succès. Un message d'activation a été envoyé à votre e-mail",
  addTable : "Ajouter un tableau",  
  newTable : "Ajouter un nouveau tableau",
  addCard : "Ajouter une carte",
  title : "Titre",
  description : "La description",
  list : "List",
  category : "Catégorie",
  "addCategory" : "Ajouter une catégorie",
  "addList" : "Ajouter une List",
  "categoryIsExist" : "La catégorie existe",
  "ListIsExist" : "La list existe",
  removeFinel: "Êtes-vous sûr de vouloir supprimer définitivement ?",
  "Invite a collaborator" : "Inviter un collaborateur",
  "invitation is sent" : "Invitation est envoyé",

};

export default fr;
